/*
 * Function: copy_interrupt_configuration_data
 * Entry:    00066644
 * Prototype: undefined copy_interrupt_configuration_data()
 */


void copy_interrupt_configuration_data(void)

{
  DAT_2000b36c = HARDWARE_INTERRUPT_CONFIG_REGISTER;
  DAT_2000b370 = HARDWARE_INTERRUPT_VALIDATION_BUFFER;
  INTERRUPT_CONFIGURATION_DATA_COPY_STATE = HARDWARE_INTERRUPT_VALIDATION_BUFFER_2;
  HARDWARE_INTERRUPT_CONFIG_REGISTER = HARDWARE_INTERRUPT_STATUS_REGISTER;
  if (HARDWARE_INTERRUPT_STATUS_REGISTER != 0) {
    HARDWARE_INTERRUPT_VALIDATION_BUFFER = HARDWARE_INTERRUPT_CONFIGURATION;
    HARDWARE_INTERRUPT_VALIDATION_BUFFER_2 = INTERRUPT_CONFIGURATION_COPY_BUFFER;
    HARDWARE_INTERRUPT_STATUS_REGISTER = 0;
    return;
  }
  return;
}


